datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://sample_monitor_deploy-prometheus-1:9090
    editable: true
    isDefault: true
