name: Build image

on:
  push:
    branches: [ "main", "release-1" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: dvdolgy/${{ github.repository }}
          tag: latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          cache: true
          cache_registry: ${{ github.repository }}/cache
